### ISSUE TITLE
Please remove "rotterdam.nl" from the list. It has been working for some time.

### ISSUE THREAD

**Issue by vdukhovni** [danefail/list#15]
The "rotterdam.nl" domain has been working correctly since early December.  If this list is to be trusted, domains need to be rechecked regularly, and resolved domains removed promptly.  Stale records should not be allowed to linger.

**Comment by desh-se** [comment]
Thank you. I agree, and have committed a script a795d71cf3471f254f692c69fdebb58da7556e76 that I will cron regularly.
