### ISSUE TITLE
Please add domains MX-hosted by mail.abanto-zierbena.org

### ISSUE THREAD

**Issue by vdukhovni** [danefail/list#20]
TLSA records of primary MX (mail.abanto-zierbena.org) don't match reality, only the backup MX (gate1.kender.com) TLSA records work.  Notified 2017/07/27, no action as yet.
```
abantoyciervana.org
abanto-zierbena.org
abantoyciervana.com
abanto-zierbena.com
```

**Comment by desh-se** [comment]
Closed by 1ef6497a639373c99f8b6f21053dc70ad6fda98b
